### ISSUE TITLE
Rake task for adding users should be interactive

### ISSUE THREAD

**Issue by maxfierke** [maxfierke/resumis#35]
It's a bit clunky to have to specify so many arguments on the CLI (including password, which is a big no-no)

The rake task should be rewrite using Thor or something to enable interactive usage with prompts and password masking.

**Comment by GustavoCaso** [comment]
I can help with this one

**Comment by GustavoCaso** [comment]
@maxfierke we can close the issue 😄

**Comment by maxfierke** [comment]
Right you are!
